steps:
  # Build Docker image with build-time args for NEXT_PUBLIC_ vars
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_ONCHAINKIT_API_KEY=$$NEXT_PUBLIC_ONCHAINKIT_API_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_COINBASE_PROJECT_ID=$$NEXT_PUBLIC_COINBASE_PROJECT_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_RESEND_API_KEY=$$NEXT_PUBLIC_RESEND_API_KEY'
      - '--build-arg'
      - 'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=$$NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'
      - '--build-arg'
      - 'NEXT_PUBLIC_UNICHAIN_RPC_URL=https://mainnet.unichain.org'
      - '--build-arg'
      - 'NEXT_PUBLIC_CHAIN_MODE=mainnet'
      - '--build-arg'
      - 'NEXT_PUBLIC_AGENT_URL=https://foodyepay-agent-443906211776.us-east1.run.app'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:$BUILD_ID'
      - '-t'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:latest'
      - '.'
    secretEnv:
      - 'NEXT_PUBLIC_ONCHAINKIT_API_KEY'
      - 'NEXT_PUBLIC_COINBASE_PROJECT_ID'
      - 'NEXT_PUBLIC_RESEND_API_KEY'
      - 'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'

  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:$BUILD_ID'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'unifoody'
      - '--image'
      - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:$BUILD_ID'
      - '--region'
      - 'us-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '1'
      - '--max-instances'
      - '10'
      - '--port'
      - '8080'
      - '--add-cloudsql-instances'
      - '$PROJECT_ID:us-east1:unifoody-db'
      - '--set-secrets'
      - 'DATABASE_URL=DATABASE_URL:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,TWILIO_PHONE_NUMBER=TWILIO_PHONE_NUMBER:latest,COINBASE_API_KEY=COINBASE_API_KEY:latest,COINBASE_API_SECRET=COINBASE_API_SECRET:latest,SWAP_WALLET_PRIVATE_KEY=SWAP_WALLET_PRIVATE_KEY:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,AVOS_WEBHOOK_SECRET=AVOS_WEBHOOK_SECRET:latest,ADMIN_API_KEY=ADMIN_API_KEY:latest,GOOGLE_MAPS_API_KEY=GOOGLE_MAPS_API_KEY:latest,SQUARE_APPLICATION_ID=SQUARE_APPLICATION_ID:latest,SQUARE_APPLICATION_SECRET=SQUARE_APPLICATION_SECRET:latest,SQUARE_ACCESS_TOKEN=SQUARE_ACCESS_TOKEN:latest,SQUARE_ENVIRONMENT=SQUARE_ENVIRONMENT:latest'
      - '--set-env-vars'
      - 'NODE_ENV=production,NEXT_PUBLIC_CHAIN_ID=130,NEXT_PUBLIC_UNICHAIN_RPC_URL=https://mainnet.unichain.org,NEXT_PUBLIC_CHAIN_MODE=mainnet,NEXT_PUBLIC_COINBASE_ENV=production,NEXT_PUBLIC_AGENT_URL=https://foodyepay-agent-443906211776.us-east1.run.app,NEXT_PUBLIC_PAYMENT_LINK_BASE_URL=https://unifoody.com'

# Build-time secrets from Secret Manager (for NEXT_PUBLIC_ vars baked into JS bundle)
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_ONCHAINKIT_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_ONCHAINKIT_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_COINBASE_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_COINBASE_PROJECT_ID'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_RESEND_API_KEY/versions/latest
      env: 'NEXT_PUBLIC_RESEND_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID/versions/latest
      env: 'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID'

images:
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:$BUILD_ID'
  - 'us-east1-docker.pkg.dev/$PROJECT_ID/unifoody/unifoody:latest'

options:
  logging: CLOUD_LOGGING_ONLY
